# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('thumbnail', models.ImageField(upload_to='cartoons/images')),
                ('date', models.DateField()),
                ('seo_title', models.CharField(max_length=250)),
                ('seo_description', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140)),
                ('thumbnail', models.ImageField(upload_to='cartoons/images')),
                ('date', models.DateField()),
                ('video', models.FileField(upload_to='cartoons/videos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoons.Category')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Post'),
        ),
    ]
